# _config.yml

title: Muhammet Abdullah Şahin - CV
email: iletisim@ornek.com
description: >- # Google'da görünecek açıklama
  Muhammet Abdullah Şahin'in profesyonel CV'si. Python, Flutter ve AI alanında çalışmalar.
baseurl: "" 
url: "https://cv.masahin.dev" 

# --- TEMA SEÇİMİ ---
# Seçenekler: 'modern-ide' VEYA 'corporate-blue'
cv_theme: "modern-ide" 

# --- SEO & EKLENTİLER ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# PDF İndirme Özelliği İçin
enable_pdf_download: true