# Site Settings
title: Özgeçmiş
url: 'https://cv.masahin.dev'

description: A beautiful Jekyll theme for creating resume
theme_skin: blue
chrome_mobile_color:

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Default language for the site
default_lang: tr

# Supported languages
languages:
  - tr
  - en

# Data files by language (adlandırma için kolay erişim)
data_files:
  tr: data-tr
  en: data-en
